local function map(mode, lhs, rhs, opts)
  local options = { noremap = true }
  if opts then
    options = vim.tbl_extend("force", options, opts)

  end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

-- Vim for Norman

map('', 'Q', ':q<cr>', {})
map('', 'S', ':w<cr>', {})
map('', 'd', 'e', {})
map('', 'f', 'r', {})
map('', 'k', 't', {})
map('', 'j', 'y', {})
map('', 'r', 'i', {})
map('', 'l', 'o', {})
map('', 'h', 'p', {})
map('', 'e', 'd', {})
map('', 't', 'f', {})
map('', 'y', 'h', {})
map('', 'n', 'j', {})
map('', 'i', 'k', {})
map('', 'o', 'l', {})
map('', 'p', 'n', {})
map('', 'D', 'E', {})
map('', 'F', 'R', {})
map('', 'K', 'T', {})
map('', 'J', 'Y', {})
map('', 'R', 'I', {})
map('', 'L', 'O', {})
map('', 'H', 'P', {})
map('', 'E', 'D', {})
map('', 'T', 'F', {})
map('', 'Y', '^', {})
map('', 'N', '5j', {})
map('', 'I', '5k', {})
map('', 'O', '$', {})
map('', 'P', 'N', {})
map('', '<leader>w', '<C-w>w', {})
map('', '<leader>i', '<C-w>k', {})
map('', '<leader>n', '<C-w>j', {})
map('', '<leader>y', '<C-w>h', {})
map('', '<leader>o', '<C-w>l', {})
map('n', '<S-Tab>', ':bn<cr>', {})
map('n', '<C-t>', ':tabnew split<cr>', {})
map('n', '<leader><cr>', ':nohlsearch<cr>', {})
map('n', 'X', ':bd|bp<cr>', {})
-- Telescope Keymap
map('n', '<leader>se', '<cmd>Telescope find_files<cr>', {})
map('n', '<leader>sg', '<cmd>Telescope live_grep<cr>', {})
map('n', '<leader>sb', '<cmd>Telescope buffers<cr>', {})
-- Nvim-Tree Keymap
map('n', '<leader>ee', '<cmd>NvimTreeToggle<cr>', {})
-- Buffer-Line Keymap
map('n', '<leader>1', '<cmd>BufferLineGoToBuffer 1<cr>', {})
map('n', '<leader>2', '<cmd>BufferLineGoToBuffer 2<cr>', {})
map('n', '<leader>3', '<cmd>BufferLineGoToBuffer 3<cr>', {})
map('n', '<leader>4', '<cmd>BufferLineGoToBuffer 4<cr>', {})
map('n', '<leader>5', '<cmd>BufferLineGoToBuffer 5<cr>', {})
map('n', '<leader>6', '<cmd>BufferLineGoToBuffer 6<cr>', {})
map('n', '<leader>7', '<cmd>BufferLineGoToBuffer 7<cr>', {})
map('n', '<leader>8', '<cmd>BufferLineGoToBuffer 8<cr>', {})
map('n', '<leader>9', '<cmd>BufferLineGoToBuffer 9<cr>', {})
map('n', '<leader>bn', '<cmd>BufferLineCycleNext<cr>', {})
map('n', '<leader>bi', '<cmd>BufferLineCyclePrev<cr>', {})
map('n', '<leader>bp', '<cmd>BufferLinePick<cr>', {})
-- toggleterm Keymap
map('n', '<leader>T', '<cmd>ToggleTerm<cr>', {})
-- format
map('n', '<leader>F', '<cmd>lua vim.lsp.buf.format { async = true } <cr>', {})
map('n', '<leader>h', ':call mdip#MarkdownClipboardImage()<cr>', {})
